[package]
name = "sniper-analytics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.80"

[dependencies]
sniper-core = { path = "../sniper-core" }
sniper-telemetry = { path = "../sniper-telemetry" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }