version: 2
updates:
  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "attakdefand"
    labels:
      - "dependencies"
      - "rust"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "attakdefand"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/infra/docker"
    schedule:
      interval: "weekly"
    reviewers:
      - "attakdefand"
    labels:
      - "dependencies"
      - "docker"