version: "3.9"
services:
  nats:
    image: nats:2
    command: ["-js","-m","8222"]
    ports: ["4222:4222","8222:8222"]
  gateway:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.svc-gateway
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
    ports: ["8080:8080"]
  signals:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-signals }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  strategy:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-strategy }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  executor:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-executor }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  risk:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-risk }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  cex:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-cex }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  nft:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-nft }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  policy:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-policy }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  storage:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-storage }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
  analytics:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-analytics }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
    ports: ["3003:3003"]
  backtest:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-backtest }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
    ports: ["3004:3004"]
  dashboard:
    build: { context: .., dockerfile: infra/docker/Dockerfile.svc-dashboard }
    environment: [ "RUST_LOG=info" ]
    depends_on: [ nats ]
    ports: ["3005:3005"]