FROM rust:1.90 as build
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y pkg-config libssl-dev && \
    cargo build --release -p svc-nft

FROM debian:stable-slim
WORKDIR /app
COPY --from=build /app/target/release/svc-nft /usr/local/bin/svc-nft
ENV RUST_LOG=info
CMD ["svc-nft"]
