[package]
name = "sniper-amm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
sniper-core = { version = "0.1.0", path = "../sniper-core" }
