# Comprehensive Risk Management Configuration
# This file contains advanced risk parameters for professional trading

# Global Position Management
[portfolio]
max_daily_loss_percent = 3.0
max_weekly_loss_percent = 8.0
max_monthly_loss_percent = 15.0
max_portfolio_exposure_percent = 25.0
max_concurrent_positions = 15
default_position_size_percent = 1.0

# Individual Position Risk
[position]
max_position_loss_percent = 10.0
max_position_size_percent = 5.0
min_position_size_usd = 100
max_correlation_risk = 0.7

# Trading Parameters
[trading]
max_slippage_bps = 200  # 2%
max_gas_price_gwei = 100
transaction_timeout_secs = 60
cooldown_secs = 15
min_liquidity_usd = 5000

# Honeypot and Scam Detection
[honeypot]
sell_test_enabled = true
ownership_check = true
mint_function_check = true
transfer_fee_check = true
max_ownership_percent = 10.0
min_token_age_days = 1
require_audit = false

# Liquidity Risk
[liquidity]
min_liquidity_ratio = 0.1
lp_locked_min_days = 5
require_lp_lock = true
max_price_impact_percent = 3.0

# Correlation Risk Management
[correlation]
enabled = true
max_correlation = 0.8
time_window_hours = 24
assets_to_monitor = ["WETH", "WBTC", "USDC", "USDT"]

# Stop Loss Configuration
[stop_loss]
default_stop_loss_percent = 10.0
trailing_stop_enabled = true
trailing_stop_percent = 5.0
hard_stop_loss_percent = 25.0

# Take Profit Configuration
[take_profit]
default_take_profit_percent = 30.0
partial_take_profit_percent = 15.0
partial_take_profit_ratio = 0.5

# Market Risk
[market]
max_volatility_threshold = 2.0
max_drawdown_percent = 5.0
blacklisted_tokens = []
whitelisted_tokens = []

# Time-based Risk Controls
[time]
trading_hours_start = "09:00"
trading_hours_end = "16:00"
high_risk_hours_start = "14:00"
high_risk_hours_end = "15:00"
risk_multiplier_during_high_risk = 1.5

# Emergency Controls
[emergency]
kill_switch_enabled = true
max_consecutive_losses = 5
auto_pause_after_losses = true
manual_review_required_after_losses = 3