name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    name: Debug Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets Availability
        run: |
          echo "TELEGRAM_BOT_TOKEN present: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
          echo "TELEGRAM_CHAT_ID present: ${{ secrets.TELEGRAM_CHAT_ID != '' }}"
          echo "TELEGRAM_BOT_TOKEN length: ${#TELEGRAM_BOT_TOKEN}"
          echo "TELEGRAM_CHAT_ID length: ${#TELEGRAM_CHAT_ID}"